#!/usr/bin/env just --justfile
name := 'wlrix-assets'

rootdir := ''
prefix := '/usr'

usrdir := absolute_path(clean(rootdir / prefix))
# `share`, not `lib`: these are architecture-independent data files, and a wallpaper is exactly
# what `share` is for. The subdirectory is named for the desktop rather than dropped into
# `share/backgrounds`, which is a distribution's to arrange and not ours to add to.
sharedir := usrdir / 'share' / 'wlrix'
wallpaperdir := sharedir / 'wallpapers'
# The pictures on minimized-window icons, one per application id plus a `default.png`. Beside
# the wallpapers rather than under `share/icons`, because nothing resolves these by icon-theme
# name: `wlrix-compositor` looks them up by app id under `wlrix/images` on the XDG data path,
# and a user overrides one by dropping a file in `~/.local/share/wlrix/images`.
imagedir := sharedir / 'images'

# The cursor theme goes under `share/icons/<theme>/`, **not** under `share/wlrix`, because that
# is the only place an XCursor loader looks: libXcursor, libwayland-cursor and the `xcursor`
# crate the compositor uses all walk XDG_DATA_DIRS/icons (plus ~/.icons and a couple of legacy
# paths), and none of them can be told about a private directory without XCURSOR_PATH.
cursorname := 'sgi'
icondir := usrdir / 'share' / 'icons'
cursordir := icondir / cursorname
# The icon theme goes beside it, for the same reason and to the same place: every icon loader
# on the machine -- the `freedesktop-icons` crate the Rust components use, wlRIX's own
# XdgIconTheme in the C# apps, and GTK and Qt for anything else running here -- finds a theme
# by *name* under XDG_DATA_DIRS/icons and nowhere else.
iconname := 'wlrix'
iconthemedir := icondir / iconname
# Where the theme is looked for at *runtime*, which is not where it is written when DESTDIR is
# set: a staged install is assembled under rootdir and runs from prefix. Only the message at the
# end of `install` uses this -- naming the staging directory there would be telling whoever
# reads it to set XCURSOR_PATH to a path that will not exist on the machine.
runtime-icondir := clean(prefix / 'share' / 'icons')

# The GTK stylesheets go under `share/themes/<theme>/`, found on XDG_DATA_DIRS the same way the
# cursors are. Their titlebar assets are generated by `wlrix-compositor --dump-gtk-theme` out of
# the window frame's own drawing code, so a GTK application's headerbar is the titlebar row the
# compositor would have drawn around it.
#
# There is no `index.theme` and `gtk-theme-name` is never set to this: it is a pair of
# stylesheets rather than a complete GTK theme, and libadwaita ignores `gtk-theme-name` anyway.
# `wlrix-settings-daemon` points the user's own gtk.css at these with an @import, which GTK 3,
# GTK 4 and libadwaita all honour.
themename := 'wlRIX'
themedir := usrdir / 'share' / 'themes' / themename
runtime-themedir := clean(prefix / 'share' / 'themes')

# List available recipes.
default:
  @just --list

# Nothing to build. This repo is data, and the one thing that *is* generated from it -- the
# palette modules in wlrix-avalonia, wlrix-compositor, wlrix-greeter and wlrix-desktop -- is
# generated into those repos and checked in there. `just palette` in wlrix-epoch does it.
build:
  @echo "nothing to build: {{name}} is data"

# Check the palette against the IRIX reference it was transcribed from.
[doc("Re-verify the palette against the IRIX reference")]
test:
  python3 tools/verify-palette.py

# Install the shared data files.
#
# Everything here is installed except `palette/`, which is a *build* input: `tools/palettegen`
# resolves it ahead of time into native sources that are checked in to the consuming repos,
# precisely so nothing parses it at runtime. Installing it would put a file on disk that
# nothing reads and that could drift from the baked values without anyone noticing.
#
# `icons/` goes under `share/icons/<theme>/` beside the cursors; `images/` under
# `share/wlrix/` beside the wallpapers.
#
# Deliberately does not build -- there is nothing to build -- but it is still run as root, and
# the other components' justfiles all say this in the same place:
#
#     sudo just install
[doc("Install the shared data files (run as root)")]
install:
  #!/usr/bin/env bash
  set -euo pipefail
  install -d '{{wallpaperdir}}'
  # `-m0644` and one at a time rather than `cp -r`: the repo directory carries a `.gitkeep`,
  # and a recursive copy would install it.
  for f in wallpapers/*.png wallpapers/*.rgb wallpapers/*.jpg; do
      [ -e "$f" ] || continue
      install -Dm0644 "$f" '{{wallpaperdir}}'/"$(basename "$f")"
      echo "installed {{wallpaperdir}}/$(basename "$f")"
  done

  # The minimized-window icon pictures. PNG only: the compositor builds with `wlrix-ui`'s
  # `png` feature and not its `svg` one, so an SVG dropped here would be found by name and
  # then silently fail to decode.
  #
  # **Links stay links**, the way the cursor and icon themes below do, and for the same
  # reason: an alias here is one drawing under a second name -- `Alacritty.png` pointing at
  # `com.wlrix.terminal.png`, because a terminal emulator with no artwork of its own should
  # look like the wlRIX one rather than fall back to `default.png`. `install` dereferences,
  # so a plain loop would write the whole 11K picture out again per alias.
  install -d '{{imagedir}}'
  for f in images/*.png; do
      [ -e "$f" ] || continue
      name="$(basename "$f")"
      if [ -L "$f" ]; then
          # Relative targets, all within this one directory, so the link is correct wherever
          # the pictures land -- including a staged install under DESTDIR.
          ln -sfn "$(readlink "$f")" '{{imagedir}}'/"$name"
          echo "linked {{imagedir}}/$name -> $(readlink "$f")"
      else
          install -Dm0644 "$f" '{{imagedir}}'/"$name"
          echo "installed {{imagedir}}/$name"
      fi
  done

  # The cursor theme, entry by entry rather than `cp -r`, because **the symlinks have to stay
  # symlinks**. 72 of the theme's 121 entries are links -- the legacy X11 names, the MD5-named
  # ones themes use for drag-and-drop, and the modern CSS names -- pointing at 49 real files.
  # `install` dereferences, so a loop of `install -Dm0644` would write 121 separate cursors and
  # more than double the size for nothing.
  install -d '{{cursordir}}/cursors'
  for f in cursors/{{cursorname}}/index.theme cursors/{{cursorname}}/cursor.theme; do
      install -Dm0644 "$f" '{{cursordir}}'/"$(basename "$f")"
  done
  for f in cursors/{{cursorname}}/cursors/*; do
      name="$(basename "$f")"
      if [ -L "$f" ]; then
          # Relative targets, all within this one directory, so the link is correct wherever
          # the theme lands -- including a staged install under DESTDIR.
          ln -sfn "$(readlink "$f")" '{{cursordir}}/cursors/'"$name"
      else
          install -Dm0644 "$f" '{{cursordir}}/cursors/'"$name"
      fi
  done
  echo "installed {{cursordir}} ({{cursorname}} cursor theme)"

  # The icon theme. Entry by entry and links kept as links, for the cursors' reason: a name a
  # MIME type resolves to is often the same drawing under another name, and `install`
  # dereferences -- so a recursive copy would write the same SVG out once per alias.
  #
  # index.theme is what makes this a theme rather than a directory of files. Without it every
  # loader skips the whole tree, with no error anywhere, and the desktop quietly keeps using
  # Adwaita.
  install -Dm0644 icons/{{iconname}}/index.theme '{{iconthemedir}}'/index.theme
  for d in icons/{{iconname}}/*/*/; do
      sub="${d#icons/{{iconname}}/}"
      install -d '{{iconthemedir}}'/"$sub"
      for f in "$d"*; do
          [ -e "$f" ] || continue
          name="$(basename "$f")"
          if [ -L "$f" ]; then
              # Relative targets, so the link is correct wherever the theme lands, including a
              # staged install under DESTDIR.
              ln -sfn "$(readlink "$f")" '{{iconthemedir}}'/"$sub$name"
          else
              install -Dm0644 "$f" '{{iconthemedir}}'/"$sub$name"
          fi
      done
  done
  echo "installed {{iconthemedir}} ({{iconname}} icon theme)"

  # The GTK theme: the hand-written stylesheets, the generated per-scheme sheets, and the
  # titlebar assets. Copied wholesale rather than file by file -- unlike the cursors there are no
  # symlinks to preserve, and the asset tree is one directory per color scheme.
  install -d '{{themedir}}'
  for d in gtk-3.0 gtk-4.0; do
      install -d '{{themedir}}'/"$d"/schemes
      install -Dm0644 "themes/{{themename}}/$d/wlrix.css" '{{themedir}}'/"$d"/wlrix.css
      for f in "themes/{{themename}}/$d"/schemes/*.css; do
          install -Dm0644 "$f" '{{themedir}}'/"$d"/schemes/"$(basename "$f")"
      done
  done
  for d in themes/{{themename}}/assets/*/; do
      scheme="$(basename "$d")"
      install -d '{{themedir}}/assets'/"$scheme"
      for f in "$d"*.svg; do
          install -Dm0644 "$f" '{{themedir}}/assets'/"$scheme"/"$(basename "$f")"
      done
  done
  echo "installed {{themedir}} ({{themename}} GTK theme)"

  echo
  echo "The compositor's default config names the {{cursorname}} theme. It is found by name"
  echo "under share/icons on any XDG data directory -- so a prefix other than /usr needs"
  echo "XCURSOR_PATH to include {{runtime-icondir}}, or the pointer falls back to"
  echo "whatever theme the machine already has."

# Remove what `install` put down.
[doc("Remove what install put down")]
uninstall:
  #!/usr/bin/env bash
  set -euo pipefail
  rm -rf '{{wallpaperdir}}'
  rm -rf '{{imagedir}}'
  # Only if this left it empty: `share/wlrix` may hold something else by then.
  rmdir '{{sharedir}}' 2>/dev/null || true
  echo "removed the wlRIX wallpapers and icon pictures"
  # Our own theme directory only. `share/icons` itself belongs to the distribution and holds
  # every other theme on the machine.
  rm -rf '{{cursordir}}'
  echo "removed {{cursordir}}"
  rm -rf '{{iconthemedir}}'
  echo "removed {{iconthemedir}}"
  # Ours alone; `share/themes` holds every other theme on the machine.
  rm -rf '{{themedir}}'
  echo "removed {{themedir}}"

clean:
  @echo "nothing to clean: {{name}} is data"
