// SPDX-License-Identifier: MIT
using System.Text;

namespace Wlrix.PaletteGen;

public static class Emit
{
    private const string DoNotEdit =
        "GENERATED by wlrix-assets/tools/palettegen. Do not edit; edit the\n" +
        "    palette JSON in wlrix-assets/palette/ and re-run `just palette`.";

    /// <summary>
    /// Avalonia resource key -> palette role. Explicit rather than derived from
    /// the role name: several keys are load-bearing names the control templates
    /// already reference, and two roles deliberately share one color.
    /// </summary>
    private static readonly (string Key, string Role)[] SchemeKeys =
    [
        // Surfaces
        ("WlrixFace",                 "face"),
        ("WlrixPanel",                "panel"),
        ("WlrixReadOnly",             "readOnly"),
        ("WlrixListBackground",       "listBackground"),
        ("WlrixTextBackground",       "textFieldBackground"),
        ("WlrixTextAreaBackground",   "textBackground"),
        ("WlrixViewBackground",       "viewBackground"),
        ("WlrixMenubarBackground",    "menubarBackground"),
        ("WlrixTooltipBackground",    "tooltipBackground"),
        ("WlrixIndicatorBackground",  "indicatorBackground"),

        // Armed / pressed face
        ("WlrixSelect",               "armed"),

        // Text
        ("WlrixForeground",           "foreground"),
        ("WlrixTextForeground",       "foreground"),
        ("WlrixViewForeground",       "foreground"),
        ("WlrixTooltipForeground",    "tooltipForeground"),
        ("WlrixDisabledForeground",   "disabledForeground"),
        ("WlrixSelection",            "selectionBackground"),
        ("WlrixSelectionForeground",  "selectionForeground"),

        // Bevels. WlrixTopShadow/WlrixBottomShadow are the button-face pair,
        // which is what the bulk of the templates bevel against.
        ("WlrixTopShadow",            "faceTopShadow"),
        ("WlrixBottomShadow",         "faceBottomShadow"),
        ("WlrixPanelTopShadow",       "panelTopShadow"),
        ("WlrixPanelBottomShadow",    "panelBottomShadow"),
        ("WlrixTroughTopShadow",      "troughTopShadow"),
        ("WlrixTroughBottomShadow",   "troughBottomShadow"),
        ("WlrixTextTopShadow",        "textTopShadow"),
        ("WlrixTextBottomShadow",     "textBottomShadow"),
        ("WlrixOuterLine",            "outerLine"),

        // Pixmap buttons invert the bevel on purpose.
        ("WlrixPixmapButtonFill",         "pixmapButtonFill"),
        ("WlrixPixmapButtonTopShadow",    "pixmapButtonTopShadow"),
        ("WlrixPixmapButtonBottomShadow", "pixmapButtonBottomShadow"),

        // Scrollbars / sliders
        ("WlrixTrough",               "trough"),
        ("WlrixScrollBarControl",     "scrollBarControl"),

        // Indicators
        ("WlrixAccent",               "accent"),
        ("WlrixCheck",                "checkColor"),
        ("WlrixRadio",                "radioColor"),
        ("WlrixLightRadioFill",       "lightRadioFill"),
        ("WlrixDisabledCheck",        "disabledCheck"),
        ("WlrixSelectFill",           "selectFill"),
        ("WlrixIndicatorLight",       "indicatorLight"),

        // Status / links
        ("WlrixError",                "error"),
        ("WlrixWarning",              "warning"),
        ("WlrixInformation",          "information"),
        ("WlrixLink",                 "link"),
        ("WlrixLinkVisited",          "linkVisited"),
        ("WlrixLinkActive",           "linkActive"),

        // Alternate panel backgrounds (Base/SaSpec convention)
        ("WlrixReadOnlyPanel",        "readOnlyPanel"),
        ("WlrixReadWritePanel",       "readWritePanel"),
    ];

    /// <summary>
    /// Rust constants. Window chrome and the desktop live on the compositor
    /// side, so the title roles are emitted here and not into the Avalonia
    /// scheme, where nothing would bind them.
    /// </summary>
    private static readonly (string Name, string Role)[] RustConsts =
    [
        ("DESKTOP",             "desktop"),
        ("LOCKED",              "locked"),
        ("TITLE_ACTIVE",        "titleActive"),
        ("TITLE_ACTIVE_TEXT",   "titleActiveText"),
        ("TITLE_INACTIVE",      "titleInactive"),
        ("TITLE_INACTIVE_TEXT", "titleInactiveText"),
        ("PANEL",               "panel"),
        ("FACE",                "face"),
        ("TOP_SHADOW",          "faceTopShadow"),
        ("BOTTOM_SHADOW",       "faceBottomShadow"),
        ("OUTER_LINE",          "outerLine"),
        ("FOREGROUND",          "foreground"),
    ];

    /// <summary>
    /// What the greeter draws with. A superset of the compositor's list, because a
    /// whole Motif dialog needs every shadow pair rather than just the window chrome.
    /// </summary>
    private static readonly (string Name, string Role)[] GreeterConsts =
    [
        ("LOGIN_BACKGROUND",     "loginBackground"),
        ("PANEL",                "panel"),
        ("PANEL_TOP_SHADOW",     "panelTopShadow"),
        ("PANEL_BOTTOM_SHADOW",  "panelBottomShadow"),
        ("FACE",                 "face"),
        ("FACE_TOP_SHADOW",      "faceTopShadow"),
        ("FACE_BOTTOM_SHADOW",   "faceBottomShadow"),
        ("ARMED",                "armed"),
        ("TEXT_FIELD",           "textFieldBackground"),
        ("TEXT_TOP_SHADOW",      "textTopShadow"),
        ("TEXT_BOTTOM_SHADOW",   "textBottomShadow"),
        ("LIST_BACKGROUND",      "listBackground"),
        ("TROUGH",               "trough"),
        ("TROUGH_TOP_SHADOW",    "troughTopShadow"),
        ("TROUGH_BOTTOM_SHADOW", "troughBottomShadow"),
        ("SCROLL_BAR_CONTROL",   "scrollBarControl"),
        ("FOREGROUND",           "foreground"),
        ("DISABLED_FOREGROUND",  "disabledForeground"),
        ("SELECTION_BACKGROUND", "selectionBackground"),
        ("SELECTION_FOREGROUND", "selectionForeground"),
        ("SELECT_FILL",          "selectFill"),
        ("OUTER_LINE",           "outerLine"),
    ];

    /// <summary>
    /// Metrics the greeter draws to, as (Rust name, flattened JSON key).
    /// </summary>
    private static readonly (string Name, string Key)[] GreeterMetrics =
    [
        ("SHADOW_DEFAULT",          "shadowThickness.default"),
        ("SHADOW_SCROLL_BAR",       "shadowThickness.scrollBar"),
        ("SHADOW_SCROLLED_WINDOW",  "shadowThickness.scrolledWindow"),
        ("SHADOW_LIST",             "shadowThickness.list"),
        ("SHADOW_TEXT",             "shadowThickness.text"),
        ("SCROLL_BAR_SIZE",         "scrollBarSize"),
        ("INDICATOR_SIZE",          "indicatorSize"),
        ("TEXT_MARGIN_HEIGHT",      "textMargin.height"),
        ("TEXT_MARGIN_WIDTH",       "textMargin.width"),
    ];

    private static Rgb Get(Palette p, string role) =>
        p.Resolved.TryGetValue(role, out var c)
            ? c
            : throw new InvalidDataException($"palette '{p.Id}' has no role '{role}'");

    public static string Scheme(Palette p, string schemeName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!--");
        sb.AppendLine($"    {DoNotEdit}");
        sb.AppendLine();
        sb.AppendLine($"    {p.Name}");
        sb.AppendLine($"    Source: {p.Source}");
        sb.AppendLine("-->");
        sb.AppendLine("<ResourceDictionary xmlns=\"https://github.com/avaloniaui\"");
        sb.AppendLine("                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">");

        foreach (var (key, role) in SchemeKeys)
            sb.AppendLine($"    <Color x:Key=\"{key}Color\">{Get(p, role).Hex}</Color>");

        sb.AppendLine("</ResourceDictionary>");
        return sb.ToString();
    }

    /// <summary>
    /// The brush layer is the same for every scheme (each brush just points at
    /// its Color key), so it is emitted once instead of being copied into all
    /// of them.
    /// </summary>
    public static string Brushes(Palette p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!--");
        sb.AppendLine($"    {DoNotEdit}");
        sb.AppendLine();
        sb.AppendLine("    One SolidColorBrush per Color key. Scheme-independent: swapping the");
        sb.AppendLine("    merged scheme dictionary repoints every brush through DynamicResource.");
        sb.AppendLine("-->");
        sb.AppendLine("<ResourceDictionary xmlns=\"https://github.com/avaloniaui\"");
        sb.AppendLine("                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">");

        foreach (var (key, _) in SchemeKeys)
            sb.AppendLine($"    <SolidColorBrush x:Key=\"{key}\" Color=\"{{DynamicResource {key}Color}}\" />");

        sb.AppendLine("</ResourceDictionary>");
        return sb.ToString();
    }

    public static string Rust(Palette p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// SPDX-License-Identifier: GPL-3.0-or-later");
        sb.AppendLine("//");
        sb.AppendLine($"// {DoNotEdit.Replace("\n    ", "\n// ")}");
        sb.AppendLine("//");
        sb.AppendLine($"// {p.Name}");
        sb.AppendLine($"// Source: {p.Source}");
        sb.AppendLine();
        sb.AppendLine("// The palette is emitted whole; window chrome and other consumers land");
        sb.AppendLine("// over time, so not every constant has a caller yet.");
        sb.AppendLine("#![allow(dead_code)]");
        sb.AppendLine();
        sb.AppendLine("use smithay::backend::renderer::Color32F;");
        sb.AppendLine();

        foreach (var (name, role) in RustConsts)
        {
            var c = Get(p, role);
            sb.AppendLine($"/// `{c.Hex}`");
            sb.AppendLine($"pub const {name}: Color32F = Color32F::new(");
            sb.AppendLine($"    {c.R / 255.0:F6}, {c.G / 255.0:F6}, {c.B / 255.0:F6}, 1.0,");
            sb.AppendLine(");");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// The greeter's palette. Not smithay's <c>Color32F</c>: the greeter draws into a
    /// <c>wl_shm</c> Argb8888 buffer, so a packed u32 is one store per pixel and needs
    /// no rearranging.
    /// </summary>
    public static string RustGreeter(Palette p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// SPDX-License-Identifier: GPL-3.0-or-later");
        sb.AppendLine("//");
        sb.AppendLine("// GENERATED by wlrix-assets/tools/palettegen. Do not edit; edit the");
        sb.AppendLine("// palette JSON in wlrix-assets/palette/ and re-run `just palette`.");
        sb.AppendLine("#![allow(dead_code)]");
        sb.AppendLine();
        sb.AppendLine("use super::Rgb;");
        sb.AppendLine();

        foreach (var (name, role) in GreeterConsts)
        {
            var c = Get(p, role);
            sb.AppendLine($"/// `{c.Hex}`");
            sb.AppendLine($"pub const {name}: Rgb = Rgb(0xff_{c.R:x2}{c.G:x2}{c.B:x2});");
            sb.AppendLine();
        }

        sb.AppendLine("/// Motif geometry, in logical pixels.");
        sb.AppendLine("pub mod metrics {");
        foreach (var (name, key) in GreeterMetrics)
        {
            if (!p.Metrics.TryGetValue(key, out var value))
                throw new InvalidDataException($"palette '{p.Id}' has no metric '{key}'");
            sb.AppendLine($"    /// `{key}`");
            sb.AppendLine($"    pub const {name}: i32 = {value};");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }
}
