// SPDX-License-Identifier: MIT
using System.Text;

namespace Wlrix.PaletteGen;

public static class Emit
{
    private const string DoNotEdit =
        "GENERATED by wlrix-assets/tools/palettegen. Do not edit; edit the\n" +
        "    palette JSON in wlrix-assets/palette/ and re-run `just palette`.";

    /// <summary>
    /// Avalonia resource key -> palette role. Explicit rather than derived from
    /// the role name: several keys are load-bearing names the control templates
    /// already reference, and two roles deliberately share one color.
    /// </summary>
    private static readonly (string Key, string Role)[] SchemeKeys =
    [
        // Surfaces
        ("WlrixFace",                 "face"),
        ("WlrixPanel",                "panel"),
        ("WlrixReadOnly",             "readOnly"),
        ("WlrixListBackground",       "listBackground"),
        ("WlrixTextBackground",       "textFieldBackground"),
        ("WlrixTextAreaBackground",   "textBackground"),
        ("WlrixViewBackground",       "viewBackground"),
        ("WlrixMenubarBackground",    "menubarBackground"),
        ("WlrixTooltipBackground",    "tooltipBackground"),
        ("WlrixIndicatorBackground",  "indicatorBackground"),

        // Armed / pressed face
        ("WlrixSelect",               "armed"),

        // Text
        ("WlrixForeground",           "foreground"),
        ("WlrixTextForeground",       "foreground"),
        ("WlrixViewForeground",       "foreground"),
        ("WlrixTooltipForeground",    "tooltipForeground"),
        ("WlrixDisabledForeground",   "disabledForeground"),
        ("WlrixSelection",            "selectionBackground"),
        ("WlrixSelectionForeground",  "selectionForeground"),

        // Bevels. WlrixTopShadow/WlrixBottomShadow are the button-face pair,
        // which is what the bulk of the templates bevel against.
        ("WlrixTopShadow",            "faceTopShadow"),
        ("WlrixBottomShadow",         "faceBottomShadow"),
        ("WlrixPanelTopShadow",       "panelTopShadow"),
        ("WlrixPanelBottomShadow",    "panelBottomShadow"),
        ("WlrixTroughTopShadow",      "troughTopShadow"),
        ("WlrixTroughBottomShadow",   "troughBottomShadow"),
        ("WlrixTextTopShadow",        "textTopShadow"),
        ("WlrixTextBottomShadow",     "textBottomShadow"),
        ("WlrixOuterLine",            "outerLine"),

        // Pixmap buttons invert the bevel on purpose.
        ("WlrixPixmapButtonFill",         "pixmapButtonFill"),
        ("WlrixPixmapButtonTopShadow",    "pixmapButtonTopShadow"),
        ("WlrixPixmapButtonBottomShadow", "pixmapButtonBottomShadow"),

        // Scrollbars / sliders
        ("WlrixTrough",               "trough"),
        ("WlrixScrollBarControl",     "scrollBarControl"),

        // Indicators
        ("WlrixAccent",               "accent"),
        ("WlrixCheck",                "checkColor"),
        ("WlrixRadio",                "radioColor"),
        ("WlrixLightRadioFill",       "lightRadioFill"),
        ("WlrixDisabledCheck",        "disabledCheck"),
        ("WlrixSelectFill",           "selectFill"),
        ("WlrixIndicatorLight",       "indicatorLight"),

        // Status / links
        ("WlrixError",                "error"),
        ("WlrixWarning",              "warning"),
        ("WlrixInformation",          "information"),
        ("WlrixLink",                 "link"),
        ("WlrixLinkVisited",          "linkVisited"),
        ("WlrixLinkActive",           "linkActive"),

        // Alternate panel backgrounds (Base/SaSpec convention)
        ("WlrixReadOnlyPanel",        "readOnlyPanel"),
        ("WlrixReadWritePanel",       "readWritePanel"),
    ];

    private static Rgb Get(Palette p, string role) =>
        p.Resolved.TryGetValue(role, out var c)
            ? c
            : throw new InvalidDataException($"palette '{p.Id}' has no role '{role}'");

    public static string Scheme(Palette p, string schemeName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!--");
        sb.AppendLine($"    {DoNotEdit}");
        sb.AppendLine();
        sb.AppendLine($"    {p.Name}");
        sb.AppendLine($"    Source: {p.Source}");
        sb.AppendLine("-->");
        sb.AppendLine("<ResourceDictionary xmlns=\"https://github.com/avaloniaui\"");
        sb.AppendLine("                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">");

        foreach (var (key, role) in SchemeKeys)
            sb.AppendLine($"    <Color x:Key=\"{key}Color\">{Get(p, role).Hex}</Color>");

        sb.AppendLine("</ResourceDictionary>");
        return sb.ToString();
    }

    /// <summary>
    /// The brush layer is the same for every scheme (each brush just points at
    /// its Color key), so it is emitted once instead of being copied into all
    /// of them.
    /// </summary>
    public static string Brushes(Palette p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!--");
        sb.AppendLine($"    {DoNotEdit}");
        sb.AppendLine();
        sb.AppendLine("    One SolidColorBrush per Color key. Scheme-independent: swapping the");
        sb.AppendLine("    merged scheme dictionary repoints every brush through DynamicResource.");
        sb.AppendLine("-->");
        sb.AppendLine("<ResourceDictionary xmlns=\"https://github.com/avaloniaui\"");
        sb.AppendLine("                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">");

        foreach (var (key, _) in SchemeKeys)
            sb.AppendLine($"    <SolidColorBrush x:Key=\"{key}\" Color=\"{{DynamicResource {key}Color}}\" />");

        sb.AppendLine("</ResourceDictionary>");
        return sb.ToString();
    }

    /// <summary>
    /// The Rust side, as one file: <c>wlrix-ui/src/palette/generated.rs</c>.
    ///
    /// This replaced three hand-kept subsets -- 13 constants for the compositor in smithay's
    /// <c>Color32F</c>, 23 for the greeter and 12 for the desktop in a packed <c>u32</c> --
    /// which between them had three names for one color and left the window chrome bound to
    /// none of them. One struct, every role, one color type, and the palette is a value a
    /// running program can swap rather than a constant baked into the call site.
    /// </summary>
    public static string RustUi(IReadOnlyList<Palette> palettes, Palette standard)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// SPDX-License-Identifier: GPL-3.0-or-later");
        sb.AppendLine("//");
        sb.AppendLine($"// {DoNotEdit.Replace("\n    ", "\n// ")}");
        sb.AppendLine("//");
        sb.AppendLine("// One `Palette` per scheme and gamma bake. The struct, the role table and");
        sb.AppendLine("// every static below come from one generator run over the same JSON, so a");
        sb.AppendLine("// renamed role cannot leave the accessors behind.");
        sb.AppendLine();
        sb.AppendLine("// A palette is emitted whole; consumers land over time, so not every role");
        sb.AppendLine("// has a caller yet.");
        sb.AppendLine("#![allow(dead_code)]");
        sb.AppendLine();
        sb.AppendLine("use crate::color::Rgb;");
        sb.AppendLine();

        var roles = standard.Resolved.Keys.ToArray();
        var metrics = standard.Metrics.Keys.ToArray();

        // --- Metrics -----------------------------------------------------------------
        sb.AppendLine("/// Motif geometry, in logical pixels.");
        sb.AppendLine("///");
        sb.AppendLine("/// Travels with the colors because a bevel needs both: the shadow pair is what");
        sb.AppendLine("/// it is drawn in and the thickness is how much of it there is.");
        sb.AppendLine("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
        sb.AppendLine("pub struct Metrics {");
        foreach (var key in metrics)
        {
            sb.AppendLine($"    /// `{key}`");
            sb.AppendLine($"    pub {Snake(key)}: i32,");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // --- Palette -----------------------------------------------------------------
        sb.AppendLine("/// One resolved color scheme.");
        sb.AppendLine("///");
        sb.AppendLine("/// `Copy` and `'static`, so it is passed as `&'static Palette` and nothing that");
        sb.AppendLine("/// holds one grows a lifetime parameter.");
        sb.AppendLine("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
        sb.AppendLine("pub struct Palette {");
        sb.AppendLine("    /// The id `by_id` answers to, and what a config file names.");
        sb.AppendLine("    pub id: &'static str,");
        sb.AppendLine("    /// Human-readable, for a settings panel to list.");
        sb.AppendLine("    pub name: &'static str,");
        sb.AppendLine("    pub gamma: &'static str,");
        sb.AppendLine("    /// The scheme's own `IsDarkScheme`.");
        sb.AppendLine("    pub dark: bool,");
        sb.AppendLine("    pub metrics: Metrics,");
        foreach (var role in roles)
        {
            sb.AppendLine($"    /// `{role}` -- `{Get(standard, role).Hex}` in the default scheme.");
            sb.AppendLine($"    pub {Snake(role)}: Rgb,");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // --- Role accessors ----------------------------------------------------------
        sb.AppendLine("impl Palette {");
        sb.AppendLine("    /// Every role name, in the order the palette JSON declares them.");
        sb.AppendLine("    pub const ROLE_NAMES: &'static [&'static str] = &[");
        foreach (var role in roles) sb.AppendLine($"        \"{role}\",");
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    /// One role by its JSON name, for code that is handed a name rather than");
        sb.AppendLine("    /// writing one -- a settings panel listing what a scheme defines, or a");
        sb.AppendLine("    /// loader reading a scheme off disk. Drawing code names the field.");
        sb.AppendLine("    pub fn role(&self, name: &str) -> Option<Rgb> {");
        sb.AppendLine("        Some(match name {");
        foreach (var role in roles) sb.AppendLine($"            \"{role}\" => self.{Snake(role)},");
        sb.AppendLine("            _ => return None,");
        sb.AppendLine("        })");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// Overwrite one role, reporting whether the name was known.");
        sb.AppendLine("    ///");
        sb.AppendLine("    /// The half of the future filesystem loader that has to stay in step with the");
        sb.AppendLine("    /// struct: start from a shipped palette, `set_role` what the file overrides,");
        sb.AppendLine("    /// warn about the rest. Generated beside the fields so it cannot drift.");
        sb.AppendLine("    pub fn set_role(&mut self, name: &str, value: Rgb) -> bool {");
        sb.AppendLine("        match name {");
        foreach (var role in roles) sb.AppendLine($"            \"{role}\" => self.{Snake(role)} = value,");
        sb.AppendLine("            _ => return false,");
        sb.AppendLine("        }");
        sb.AppendLine("        true");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // --- The schemes themselves --------------------------------------------------
        foreach (var p in palettes)
        {
            sb.AppendLine($"/// {p.Name}");
            sb.AppendLine("///");
            sb.AppendLine($"/// Source: {p.Source}");
            sb.AppendLine($"pub static {ConstName(p.Id)}: Palette = Palette {{");
            sb.AppendLine($"    id: \"{p.Id}\",");
            sb.AppendLine($"    name: \"{p.Name}\",");
            sb.AppendLine($"    gamma: \"{p.Gamma}\",");
            sb.AppendLine($"    dark: {(p.Dark ? "true" : "false")},");
            sb.AppendLine("    metrics: Metrics {");
            foreach (var key in metrics)
            {
                if (!p.Metrics.TryGetValue(key, out var value))
                    throw new InvalidDataException($"palette '{p.Id}' has no metric '{key}'");
                sb.AppendLine($"        {Snake(key)}: {value},");
            }
            sb.AppendLine("    },");
            foreach (var role in roles)
            {
                var c = Get(p, role);
                sb.AppendLine($"    {Snake(role)}: Rgb(0xff_{c.R:x2}{c.G:x2}{c.B:x2}),");
            }
            sb.AppendLine("};");
            sb.AppendLine();
        }

        // --- Lookup ------------------------------------------------------------------
        sb.AppendLine("/// Every scheme this build ships, for a settings panel to offer.");
        // One line while it fits, one per line once it does not -- which is what rustfmt
        // does, and this file is checked in and run through `cargo fmt --check` in CI. Get
        // it wrong and the tree is permanently one `cargo fmt` away from what the generator
        // produces, which quietly breaks `just check-palette`.
        var all = string.Join(", ", palettes.Select(p => "&" + ConstName(p.Id)));
        var oneLine = $"pub static ALL: &[&Palette] = &[{all}];";
        if (oneLine.Length <= 100)
        {
            sb.AppendLine(oneLine);
        }
        else
        {
            sb.AppendLine("pub static ALL: &[&Palette] = &[");
            foreach (var p in palettes) sb.AppendLine($"    &{ConstName(p.Id)},");
            sb.AppendLine("];");
        }
        sb.AppendLine();
        sb.AppendLine("/// What a component draws with when nothing selects a scheme.");
        sb.AppendLine($"pub static DEFAULT: &Palette = &{ConstName(standard.Id)};");
        sb.AppendLine();
        sb.AppendLine("/// The scheme a config file or a `--palette` flag names.");
        sb.AppendLine("///");
        sb.AppendLine("/// `None` for an unknown id rather than a fallback: only the caller knows");
        sb.AppendLine("/// whether that deserves a warning and [`DEFAULT`], or is a hard error.");
        sb.AppendLine("pub fn by_id(id: &str) -> Option<&'static Palette> {");
        sb.AppendLine("    ALL.iter().copied().find(|p| p.id == id)");
        sb.AppendLine("}");

        return Trimmed(sb);
    }

    /// <summary>lowerCamel or dotted.lowerCamel -> snake_case.</summary>
    private static string Snake(string name)
    {
        var sb = new StringBuilder();
        foreach (var ch in name)
        {
            if (ch == '.') { sb.Append('_'); continue; }
            if (char.IsUpper(ch)) { sb.Append('_').Append(char.ToLowerInvariant(ch)); continue; }
            sb.Append(ch);
        }
        return sb.ToString();
    }

    /// <summary>classic-g10 -> CLASSIC_G10.</summary>
    private static string ConstName(string id) => id.Replace('-', '_').ToUpperInvariant();

    /// <summary>
    /// The built text with its trailing blank line removed, so the generated file matches
    /// what <c>cargo fmt</c> would leave and CI's format check stays quiet.
    /// </summary>
    private static string Trimmed(StringBuilder sb) => sb.ToString().TrimEnd() + "\n";
}
